Support telemetry
membraneframework/membrane_rtp_format pull request #12
Opened 2022-05-17 15:06 UTC by FelonEkonom

2022-05-30 10:07 UTC, mickel8 approved these changes

2022-05-30 14:17 UTC, mat-hek requested changes

2022-05-30 14:17 UTC, mat-hek commented on lib/membrane/rtp/payload_format.ex
> +          frame_detector: function() | nil
`function` is not much of a spec

2022-05-31 10:50 UTC, mat-hek approved these changes

2022-05-31 11:59 UTC, merged